import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('Iris.csv')
# print(df)
X = df.iloc[:,1:5]
y = df.iloc[:,5]
# print(y.value_counts())

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

y = le.fit_transform(y) #how to change in dataframe
y = pd.DataFrame(y)

# print(y)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)







# # -*- coding: utf-8 -*-
# """Copy of Welcome To Colab

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1ADjX1xe34cNblw1ryrzOr96bCDduxDnI
# """





# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt

# import tensorflow as tf
# print(tf.__version__)

# dataset = pd.read_csv('Churn_Modelling.csv')
# print(dataset.head)

# ##Dividing the data set into independent and dependent and removing the unnecessory columns
# X = dataset.iloc[:,3:13]
# y = dataset.iloc[:,13]

# print(X.head)

# ##Feature engineering one hot encoding the columns
# geography = pd.get_dummies(X['Geography'],drop_first=True)
# gender = pd.get_dummies(X['Gender'],drop_first=True)

# ##concatenate these variables
# X = X.drop(['Geography','Gender'],axis=1)
# X.head()

# X = pd.concat([X,geography,gender],axis=1)

# #splitting data in test and train
# from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test=sc.transform(X_test)

# ## Creating ANN
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense
# from tensorflow.keras.layers import LeakyReLU, PReLU, ELU, ReLU
# from tensorflow.keras.layers import Dropout

# ## Initializing the ANN
# classifier = Sequential()

# ## Adding the Input layer
# classifier.add(Dense(units=11,activation='relu'))

# #adding the first hidden layer
# classifier.add(Dense(units=7,activation = 'relu'))

# #adding the second hidden layer
# classifier.add(Dense(units=6,activation='relu'))

# #adding the output layer
# classifier.add(Dense(1,activation='sigmoid'))

# classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# import tensorflow
# opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)

# ## Early Stopping when acc isnt inc the stop the training
# import tensorflow as tf

# early_stopping = tf.keras.callbacks.EarlyStopping(
#     monitor="val_loss",
#     min_delta=0.0001,
#     patience=20,
#     verbose=1,
#     mode="auto",
#     baseline=None,
#     restore_best_weights=False,
#     start_from_epoch=0,
# )

# model_history = classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=1000,callbacks=early_stopping)

# print(model_history.history.keys())

# ## summarize history for accuracy
# plt.plot(model_history.history['accuracy'])
# plt.plot(model_history.history['val_accuracy'])
# plt.title('model accuracy')
# plt.ylabel('accuracy')
# plt.xlabel('epoch')
# plt.legend(['train','test'],loc='upper left')
# plt.show()

# ## summarize history for loss
# plt.plot(model_history.history['loss'])
# plt.plot(model_history.history['val_loss'])
# plt.title('model loss')
# plt.ylabel('loss')
# plt.xlabel('epoch')
# plt.legend(['train','test'],loc='upper left')
# plt.show()

# # prdicting the test set results
# y_pred = classifier.predict(X_test)
# y_pred = (y_pred >= 0.5)

# ## make the confusion matrix( is used to evaluate the performance of a classification model )
# from sklearn.metrics import confusion_matrix
# cm = confusion_matrix(y_test,y_pred)
# cm

# #calculate the accuracy
# from sklearn.metrics import accuracy_score
# score = accuracy_score(y_pred,y_test)
# print(score)

# #get the weights
# classifier.get_weights()

